### ISSUE TITLE
Error upon using command gulp bower

### ISSUE THREAD

**Issue by hm-chrisp** [djhsecondnature/redskylight#1]
Upon entering the command gulp bower, the command prompt crashes with error Cannot find module 'through2'. attached is a screenshot from the command prompt.
![gulp-error](https://cloud.githubusercontent.com/assets/10449624/8179679/1dd5c834-1410-11e5-9f77-63f642ee53e5.png)

**Comment by djhsecondnature** [comment]
The imagemin-jpegtran module didn't install properly. Try running 'npm install' again.
